Avoid repeated URIError in Cypress spec CI output
We were seeing multiple occurrences of the following error:

    URIError: Failed to decode param '/en/projects/%REACT_APP_PLAUSIBLE_SOURCE%'

This was making it harder to see the wood for the trees when a spec
failed.

I've set the `REACT_APP_PLAUSIBLE_SOURCE` env var to "" which is what
it's set to in `.env.example`.